logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://registry:8000/eureka/

security:
  oauth2:
    resource:
      jwk:
        key-set-uri: https://auth-service:8000/uaa/.well-known/jwks.json
      user-info-uri: http://auth-service:8000/uaa/users/current

spring:
  rabbitmq:
    host: rabbitmq