spring:
  datasource:
    url: ${POSTGRESBD_URL}
    username: ${POSTGRESBD_USERNAME}
    password: ${POSTGRESBD_PASSWORD}
    driver-class-name: org.postgresql.Driver
    # data:
    # mongodb:
    #   host: auth-mongodb
    #   username: user
    #   password: ${MONGODB_PASSWORD}
    #   database: piggymetrics
    #   port: 27017

server:
  servlet:
    context-path: /uaa
  port: 8000
