hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/uaa/**
        - id: books-service
          uri: lb://books-service
          predicates:
            - Path=/books/**
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/account/**

server:
  port: 8000
